engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_paths:
    - db/seeds.rb
    - test/
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.haml"
  - "**.rb"
exclude_paths:
- .rubocop.yml
- bin/
- .circleci/config.yml
- CHANGELOG.md
- config/
# - db/data/
- db/migrate/
- Gemfile
- Gemfile.lock
- LICENSE
- Rakefile
- README.md
